menu:
  home: Home
  archives: Archives
  tags: Tags

post:
  posted: Posted on
  read_more: Read more
  untitled: Untitled

page:
  totally: Totally
  tags: tags

footer:
  powered: Powered By
  theme: Theme Based On